services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: slorify-dev
    volumes:
      - .:/Slorify
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/slorify:/opt/slorify
    ports:
      - "5173:5173"
      - "4000:4000"
      - "5432:5432"
    env_file:
      - .env
    command: npm run dev
    dns:
      - 8.8.8.8
      - 8.8.4.4

  postgrace-db:
    image: postgres:14.20-trixie
    container_name: slorify-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: slora
      POSTGRES_PASSWORD: slorapass
      POSTGRES_DB: sloraDB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: