services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: slorify-dev
    volumes:
      - .:/Slorify
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/slorify:/opt/slorify
    ports:
      - "5173:5173"
      - "4000:4000"
      - "5432:5432"
    environment:
      - NODE_ENV=development
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATABSE_URL=postgres://slora:slorapass@postgres-db:5432/sloraDB
    command:  npm run dev

  postgrace-db:
    image: postgres:14.20-trixie
    container_name: slorify-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: slora
      POSTGRES_PASSWORD: slorapass
      POSTGRES_DB: sloraDB

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
