services:
  db:
    image: postgres:15
    container_name: slorify-db
    restart: always
    environment:
      POSTGRES_USER: slora
      POSTGRES_PASSWORD: slorapass
      POSTGRES_DB: sloraDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  slorify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Slorify
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/slorify:/opt/slorify
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATABASE_URL=postgres://slora:slorapass@db:5432/sloraDB
    command: /bin/bash -c "./scripts/wait-for-db.sh"

volumes:
  db_data:
